# Generated by Django 4.0.4 on 2023-10-27 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_localizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='category_image',
        ),
    ]
