# Generated by Django 4.0.4 on 2023-10-28 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_campo_localizacao_campo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacao',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.categorie'),
        ),
    ]
