# Generated by Django 4.0.4 on 2023-12-04 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_localizacao_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='closed_days',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='friday_closing',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='friday_opening',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='monday_closing',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='monday_opening',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='saturday_closing',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='saturday_opening',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='sunday_closing',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='sunday_opening',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='thursday_closing',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='thursday_opening',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='tuesday_closing',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='tuesday_opening',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='wednesday_closing',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='wednesday_opening',
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.campo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
