# Generated by Django 4.0.4 on 2023-12-06 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_campo_closed_days_campo_friday_closing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='campo_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
