# Generated by Django 4.0.4 on 2023-12-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_campo_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campo',
            old_name='friday_closing',
            new_name='Friday_closing',
        ),
        migrations.RenameField(
            model_name='campo',
            old_name='friday_opening',
            new_name='Friday_opening',
        ),
        migrations.RenameField(
            model_name='campo',
            old_name='monday_closing',
            new_name='Monday_closing',
        ),
        migrations.RenameField(
            model_name='campo',
            old_name='monday_opening',
            new_name='Monday_opening',
        ),
        migrations.RenameField(
            model_name='campo',
            old_name='saturday_closing',
            new_name='Saturday_closing',
        ),
        migrations.RenameField(
            model_name='campo',
            old_name='saturday_opening',
            new_name='Saturday_opening',
        ),
        migrations.RenameField(
            model_name='campo',
            old_name='sunday_closing',
            new_name='Sunday_closing',
        ),
        migrations.RenameField(
            model_name='campo',
            old_name='sunday_opening',
            new_name='Sunday_opening',
        ),
        migrations.RenameField(
            model_name='campo',
            old_name='thursday_closing',
            new_name='Thursday_closing',
        ),
        migrations.RenameField(
            model_name='campo',
            old_name='thursday_opening',
            new_name='Thursday_opening',
        ),
        migrations.RenameField(
            model_name='campo',
            old_name='tuesday_closing',
            new_name='Tuesday_closing',
        ),
        migrations.RenameField(
            model_name='campo',
            old_name='tuesday_opening',
            new_name='Tuesday_opening',
        ),
        migrations.RenameField(
            model_name='campo',
            old_name='wednesday_closing',
            new_name='Wednesday_closing',
        ),
        migrations.RenameField(
            model_name='campo',
            old_name='wednesday_opening',
            new_name='Wednesday_opening',
        ),
    ]
