# Generated by Django 4.0.4 on 2023-12-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_friday_closing_campo_friday_closing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
