# Generated by Django 4.0.4 on 2023-12-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_campo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='preco_hora',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
