# Generated by Django 4.0.4 on 2023-12-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_campo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
