# Generated by Django 4.0.4 on 2023-12-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_campo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
