# Generated by Django 4.0.4 on 2023-12-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_reserva_end_time_alter_reserva_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
