# Generated by Django 4.0.4 on 2023-12-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_reserva_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
